Adding example for Spark jobs to configure event log storage as S3
HPEEzmeral/spark-on-k8s pull request #129
Opened 2021-12-08 19:15 UTC by akshayharyani

2021-12-09 10:13 UTC, AlexNavara requested changes

2021-12-09 10:13 UTC, AlexNavara commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +        claimName: spark-hs-pvc
No need in volume and volumeMounts for this case

2021-12-09 10:13 UTC, AlexNavara commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +        name: spark-hs
No need in volume and volumeMounts for this case

2021-12-09 10:13 UTC, AlexNavara commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +  image: gcr.io/mapr-252711/spark-3.1.2:202110062359AN
This tag is outdated

2021-12-09 10:13 UTC, AlexNavara commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +  mainApplicationFile: "local:///opt/mapr/spark/spark-3.1.2/examples/jars/spark-examples_2.12-3.1.2.0-eep-SNAPSHOT.jar"
Path to the main app jar has changed in latest images

2021-12-09 10:13 UTC, AlexNavara commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +    #       it will be auto-generated with the pattern "maprfs:///apps/spark/<namespace>"
Please, add here a commented out  section about a workaround for encrypted s3a case:
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
As of now there is no way to customize truststore, therefore spark apps will trust only DF objectstore. To make it work, users need to add the options above.

2021-12-22 19:07 UTC, akshayharyani commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +        claimName: spark-hs-pvc
Removed.

2021-12-22 19:08 UTC, akshayharyani commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +  image: gcr.io/mapr-252711/spark-3.1.2:202110062359AN
Updated

2021-12-22 19:08 UTC, akshayharyani commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +    #       it will be auto-generated with the pattern "maprfs:///apps/spark/<namespace>"
Add it below

2021-12-22 19:08 UTC, akshayharyani commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +  mainApplicationFile: "local:///opt/mapr/spark/spark-3.1.2/examples/jars/spark-examples_2.12-3.1.2.0-eep-SNAPSHOT.jar"
updated

2021-12-22 19:08 UTC, akshayharyani commented on examples/spark-3.1.2/crs/spark-pi-s3-logs.yaml
> +        name: spark-hs
removed

2022-01-06 12:39 UTC, AlexNavara approved these changes
LGTM

2022-01-12 18:24 UTC, merged