EZSAP-764 - Create a Scala application that can be used as Spark example
HPEEzmeral/spark-on-k8s pull request #169
Opened 2022-06-29 00:54 UTC by mayankgarg23

2022-06-29 22:54 UTC, apurwaj2 requested changes

2022-06-29 22:54 UTC, apurwaj2 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +        (3, "p2", "s2", 50)
Try to add more distinct values of sales in case of merge operation. The old values and new values look similar. If old value was 20 make it 200 something. It's difficult to understand what changed. :)

2022-06-29 22:54 UTC, apurwaj2 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +      .show()
Show output for current version as well. It's easier to know the difference that way.

2022-06-29 22:54 UTC, apurwaj2 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +      .show(false)
Because you're showing the entire output it's difficult to read the output. If show is set to true, does it look better? Just asking

2022-06-29 23:30 UTC, mayankgarg23 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +        (3, "p2", "s2", 50)
added different values for sales to demarcate easily

2022-06-29 23:31 UTC, mayankgarg23 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +      .show()
added code to show current version and old version

2022-06-29 23:31 UTC, mayankgarg23 commented on examples/spark-3.2.0/apps/src/main/scala/com/hpe/examples/spark/delta/DeltaLakeACIDExample.scala
> +      .show(false)
added show(true), which truncates the fields. It is now better shown in the output

2022-06-30 16:20 UTC, apurwaj2 approved these changes, later dismissed

2022-06-30 17:45 UTC, AlexNavara approved these changes, later dismissed
lgtm

2022-06-30 19:50 UTC, AlexNavara requested changes

2022-06-30 19:50 UTC, AlexNavara commented on examples/spark-3.2.0/crs/deltalake/spark-delta-maprfs.yaml
> +  namespace: default
Change to 'sampletenant' to be consistent with other examples

2022-06-30 19:50 UTC, AlexNavara commented on examples/spark-3.2.0/crs/deltalake/spark-delta-maprfs.yaml
> +  arguments:
Please pull up the 'arguments' section. This is user input, and it's better to have it higher so that the user understands that the job requires arguments. Check out our 'wordcount' examples.

2022-06-30 20:36 UTC, apurwaj2 approved these changes

2022-06-30 20:44 UTC, AlexNavara approved these changes
lgtm

2022-06-30 20:45 UTC, merged