EZSPA-793 - Create an airgap utility
HPEEzmeral/spark-on-k8s pull request #178
Opened 2022-07-25 23:02 UTC by mayankgarg23

2022-07-26 12:01 UTC, apurwaj2 requested changes
The download image tool should still exist. It's a quick step to download some GCR image quickly.  The airgap utility task is to get a tar file of all the necessary spark images used by us.

2022-07-26 13:46 UTC, apurwaj2 requested changes

2022-07-26 13:46 UTC, apurwaj2 commented on tools/fetch_tag/fetch_tag.py
> +        self.get_tags_from_charts_yaml(self.charts_dir, self.chart_files, ["livy-0.8.0", "metastore-3.1.1", "mysql-operator", "spark-3.1.1", "spark-hs-3.1.1"])
Why have you included these charts?

2022-07-26 15:27 UTC, mayankgarg23 commented on tools/fetch_tag/fetch_tag.py
> +        self.get_tags_from_charts_yaml(self.charts_dir, self.chart_files, ["livy-0.8.0", "metastore-3.1.1", "mysql-operator", "spark-3.1.1", "spark-hs-3.1.1"])
these are the ones which needs to be ignored

2022-08-05 18:21 UTC, apurwaj2 requested changes

2022-08-05 18:21 UTC, apurwaj2 commented on tools/download_image/download-images.sh
> +#!/usr/bin/env bash
Rename this file to download all spark images or let's not confuse user with similar name scripts.

2022-08-05 18:21 UTC, apurwaj2 commented on tools/README.md
> +# Script to fetch image tags and download these images from GCR repository on local setup
This readme is applicable to both the scripts? Previous single image download as well as image download for all spark images?

2022-08-05 20:14 UTC, mayankgarg23 commented on tools/download_image/download-images.sh
> +#!/usr/bin/env bash
updated script name to download-single-image.sh and download-all-images.sh

2022-08-05 20:15 UTC, mayankgarg23 commented on tools/README.md
> +# Script to fetch image tags and download these images from GCR repository on local setup
There are different README.md files, one at tools/ directory level (for downloading all images) and other at donwload_image/ directory level (for downloading a single image).

2022-08-10 17:34 UTC, apurwaj2 approved these changes
lgtm

2022-08-11 17:25 UTC, merged