Adding support for deploying spark-2.4.7 operator on namespace level
HPEEzmeral/spark-on-k8s pull request #20
Opened 2021-07-02 02:51 UTC by akshayharyani

2021-07-03 04:10 UTC, Agirish commented on charts/spark-2.4.7/spark-operator-chart/templates/_helpers.tpl
> +{{- define "spark-operator.sparknamespace" -}}
Looks like we do not use the suffix '-chart' here.. But the dir name has it. Can you please change it - perhaps in a different PR?

2021-07-03 16:27 UTC, Agirish commented on charts/spark-2.4.7/spark-operator-chart/templates/_helpers.tpl
> +{{- define "spark-operator.sparknamespace" -}}
Actually it looks like community Spark operator does it this way - so let's not change it

2021-07-05 18:59 UTC, idzikovskyi commented on charts/spark-2.4.7/spark-operator-chart/templates/_helpers.tpl
> +{{ include "spark-operator.fullname" . }}-CR
As far as I know, we typically don't use uppercase abbreviations. I'd say that it would be better to change `-CR` to lowercase here to keep consistency.

2021-07-05 18:59 UTC, idzikovskyi commented on charts/spark-2.4.7/spark-operator-chart/templates/_helpers.tpl
> +{{ include "spark-operator.fullname" . }}-CRB
Same with `-CRB`.

2021-07-05 18:59 UTC, idzikovskyi commented on charts/spark-2.4.7/spark-operator-chart/templates/spark-namespace.yaml
> +  name: {{ include "spark-operator.sparknamespace" . }}
Please try to avoid situations when newline is missing at the end of file.
Files without newline at the end is hard to read in terminal.
Here is an illustration of the difference:
```
ivan@ivanhp:~$ cat newline.txt 
hello
ivan@ivanhp:~$ cat no_newline.txt 
helloivan@ivanhp:~$ 
```

2021-07-05 19:00 UTC, idzikovskyi commented
I've added minor propositions, but in general PR looks good to me.

2021-07-06 19:07 UTC, akshayharyani commented on charts/spark-2.4.7/spark-operator-chart/templates/spark-namespace.yaml
> +  name: {{ include "spark-operator.sparknamespace" . }}
I have made these changes as well as the naming convention changes you suggested.

2021-07-07 12:16 UTC, idzikovskyi submitted a review, later dismissed

2021-07-13 09:10 UTC, AlexNavara requested changes
In general, the request looks good to me, but I don't see any docs.
Please add a helm command example that will deploy the operator in a custom namespace.

2021-07-15 09:42 UTC, AlexNavara approved these changes
lgtm

2021-07-15 15:57 UTC, merged