EZAF-1056: Labels should be added through configmap instead of hardco…
HPEEzmeral/spark-on-k8s pull request #228
Opened 2023-03-14 01:52 UTC by apurwaj2

…ding the labels in the code

    Using configmap to add labels to spark applications for observability instead of hardcoding them.
    Configmap data is in the form of  label_1: "hpe-ezua/app: spark" as / is not allowed in the string used as key.

2023-03-14 07:01 UTC, AlexNavara requested changes

2023-03-14 07:01 UTC, AlexNavara commented on charts/spark-operator/spark-operator-chart/templates/_helpers.tpl
> +{{- define "autoticket-generator.sparkLabelconfigMapName" -}}
Exclude the word 'label' from namings here. Let's consider this config map just as a generic item that we use for autotix configuration.

2023-03-14 07:01 UTC, AlexNavara commented on charts/spark-operator/spark-operator-chart/values.yaml
> +  sparkLabelConfigName : "sparklabels-cm"
No need to put this in values.yaml. I believe user will not want to create the cm manually, as well as define its name.
What we really need here in values.yaml is a list of required labels.

2023-03-14 07:01 UTC, AlexNavara commented on charts/spark-operator/spark-operator-chart/templates/autotix-sparkLabel-cm.yaml
> +    label_1: "hpe-ezua/app: spark"
Let's change the cm structure to something like this:
```
data:
    spark_app_labels.yaml: |
        hpe-ezua/app: spark
        hpe-ezua/type: app-service-user
        {{ app labels read from values.yaml }}
```

2023-03-14 07:01 UTC, AlexNavara commented on charts/spark-operator/spark-operator-chart/templates/autotix-sparkLabel-cm.yaml
> +  {{ end }}
Add new line

2023-03-15 04:47 UTC, apurwaj2 commented on charts/spark-operator/spark-operator-chart/templates/autotix-sparkLabel-cm.yaml
> +    label_1: "hpe-ezua/app: spark"
Added labels through _helpers.tpl

2023-03-17 23:52 UTC, AlexNavara reviewed
It's not critical for now, but in the future we should be able to read labels from values.yaml. Please fix it now or create a follow-up task.

2023-03-17 23:52 UTC, AlexNavara commented on charts/spark-operator/spark-operator-chart/templates/_helpers.tpl
> +{{- define "autoticket-generator.sparkLabels" -}}
We should get label values from values.yaml.

2023-03-20 21:20 UTC, AlexNavara approved these changes
lgtm

2023-03-20 21:21 UTC, merged