EZAF-1822: Decouple tenant services
HPEEzmeral/spark-on-k8s pull request #238
Opened 2023-05-11 18:34 UTC by apurwaj2

Adding namespace configuration to tenant operator and tenant validator.

2023-05-12 10:18 UTC, idzikovskyi approved these changes
In general it looks good, but I'd ask @AlexNavara to also give feedback on this, since he's more familiar with the problem of passing namespaces this way in our projects.

2023-05-12 10:18 UTC, idzikovskyi commented on charts/tenant-operator/README.md
> +`helm delete tenant-operator -n <namespace>`
I'd say this piece needs to be wrapped in three backticks to be block of code, rather than inline piece.

2023-05-16 00:41 UTC, apurwaj2 commented on charts/tenant-operator/README.md
> +`helm delete tenant-operator -n <namespace>`
Thanks, Ivan!

2023-05-16 10:10 UTC, AlexNavara requested changes

2023-05-16 10:10 UTC, AlexNavara commented on charts/tenant-operator/templates/_helpers.tpl
>  {{- define "tenant-operator.namespace" -}}
Do we need this function anymore?

2023-05-16 10:10 UTC, AlexNavara commented on charts/tenant-operator/templates/operator_rbac.yaml
> +    namespace: {{ include "tenant-operator.namespace" . }}
To be removed

2023-05-16 10:10 UTC, AlexNavara commented on charts/tenant-operator/templates/validator_rbac.yaml
> +    namespace: {{ include "tenant-operator.namespace" . }}
Replace with '.Release.Namespace'

2023-05-16 16:28 UTC, apurwaj2 commented on charts/tenant-operator/templates/_helpers.tpl
>  {{- define "tenant-operator.namespace" -}}
Removed it, thank you.

2023-05-17 11:40 UTC, AlexNavara approved these changes
lgtm

2023-05-18 03:57 UTC, merged