Update values.yaml for openshift
HPEEzmeral/spark-on-k8s pull request #256
Opened 2023-11-14 06:16 UTC by skandtandon

2023-11-16 15:41 UTC, idzikovskyi requested changes
Could you also update patch number in version string in `Chart.yaml`.
And apply all this changes on Spark HistoryServer chart.
Thanks!

2023-11-16 15:41 UTC, idzikovskyi commented on charts/livy/livy-chart/values.yaml
> +
No need to add this empty line.

2023-11-16 15:41 UTC, idzikovskyi commented on charts/livy/livy-chart/values.yaml
> +  privileged: true
Can you write some comment here why we enabling privileged access.
Something like:
```
# Pod needs to run as privileged on OpenShift environment to use hostPath mounts
```

2023-11-20 17:28 UTC, idzikovskyi approved these changes

2023-11-21 04:46 UTC, abhinandantn approved these changes

2023-11-21 04:46 UTC, abhinandantn commented on charts/livy/livy-chart/values.yaml
> +  privileged: true
setting this field is needed as we are attempting chown, but can we pre-build the image with these settings so that we can avoid the need for chown ?

having privilege will it not give hackers to exploit ?

2023-11-21 15:37 UTC, merged