Add Delta Lake examples for Python and Scala
HPEEzmeral/spark-on-k8s pull request #33
Opened 2021-07-26 13:36 UTC by avenherak

2021-07-27 14:20 UTC, AlexNavara submitted a review, later dismissed
lgtm

2021-07-27 14:36 UTC, idzikovskyi commented on examples/spark-3.1.1/deltalake/spark-delta-s3-py.yaml
> +      -
Does it suppose to have empty element in the list?

Also, try to avoid having "No newline at end of file".
Files without newline at the end is hard to read in terminal.
Here is an illustration of the difference:
```
ivan@ivanhp:~$ cat newline.txt 
hello
ivan@ivanhp:~$ cat no_newline.txt 
helloivan@ivanhp:~$ 
```

2021-07-27 14:42 UTC, Agirish commented
I think we should follow the following structure:
|_examples
                  |_spark-3.1.1
                                       |_deltalake
|_samples
                  |_deltalake
                                       |_java
                                                     |_src/main/java/com/hpe/examples/spark/delta/
                                       |_python 
                                                     |_src/main/python

2021-07-27 14:42 UTC, Agirish requested changes
Please see comment above

2021-07-27 15:13 UTC, AlexNavara commented
@Agirish I'd prefer following the same examples structure as the one that's in original spark examples: https://github.com/mapr/private-spark/tree/branch-3.1.1-apache/examples It's much easier to support, and spark users are familiar with this structure. The concrete example source code can be found easily because the class/file name is included in the corresponding yaml file example.
Also, I think source code should be kept inside spark_[version] directory. This way we will be able to support examples for different spark/java/scala versions simultaneously. Otherwise, users will need to modify pom.xml manually depending on spark/java/scala version before building the examples jar.
So maybe we can just rename the root project folder from "examples" to "code-samples"?

2021-08-02 16:13 UTC, Agirish submitted a review, later dismissed
Discussed with @AlexNavara -  we agreed on structure similar to the one shown below:
```
|_examples
                  |_spark-3.1.1
                                       |_crs
                                                |_spark-delta.yaml
                                                |_spark-pi.yaml
                                       |_apps
                                                 |_java
                                                     |_src/main/java/com/hpe/examples/spark/delta/
                                                 |_python 
                                                     |_src/main/python
```

2021-08-04 09:15 UTC, AlexNavara approved these changes

2021-08-04 09:17 UTC, merged