Adding Helm chart for Spark v3.1.1 client pod
HPEEzmeral/spark-on-k8s pull request #34
Opened 2021-07-26 23:56 UTC by akshayharyani

2021-07-29 17:52 UTC, AlexNavara requested changes

2021-07-29 17:52 UTC, AlexNavara commented on charts/spark-client/spark-client/README.md
> +This will create spark operator components in already created `spark-operator-ns`. to create a new namespace during installation use the flag `-- create-namespace`  with the install command
Doc is not accurate.
Should be smth like "This will create spark client deployment in spark-ns namespace..."

2021-07-29 17:52 UTC, AlexNavara commented on charts/spark-client/spark-client/spark-client-chart/templates/_helpers.tpl
> +{{- end -}}
Add new line

2021-07-29 17:52 UTC, AlexNavara commented on charts/spark-client/spark-client/spark-client-chart/templates/imagepull.yaml
> +{{ end }}
Add new line

2021-07-29 17:52 UTC, AlexNavara commented on charts/spark-client/spark-client/spark-client-chart/values.yaml
> +  eventsDir: "/"
Add new line

2021-07-30 00:37 UTC, akshayharyani commented on charts/spark-client/spark-client/README.md
> +This will create spark operator components in already created `spark-operator-ns`. to create a new namespace during installation use the flag `-- create-namespace`  with the install command
Changed the text

2021-07-30 00:37 UTC, akshayharyani commented on charts/spark-client/spark-client/spark-client-chart/templates/imagepull.yaml
> +{{ end }}
added

2021-07-30 00:37 UTC, akshayharyani commented on charts/spark-client/spark-client/spark-client-chart/values.yaml
> +  eventsDir: "/"
added

2021-07-30 00:38 UTC, akshayharyani commented on charts/spark-client/spark-client/spark-client-chart/templates/_helpers.tpl
> +{{- end -}}
added

2021-07-30 18:39 UTC, AlexNavara approved these changes
lgtm

2021-08-02 15:10 UTC, merged