Adding apache spark-3.1.1 hive example for testing the metastore
HPEEzmeral/spark-on-k8s pull request #39
Opened 2021-08-05 16:45 UTC by apurwaj2

2021-08-05 18:01 UTC, AlexNavara requested changes

2021-08-05 18:01 UTC, AlexNavara commented on examples/spark-3.1.1/crs/hive/kv1.txt
> +238 val_238
Let's move this file to application resources instead of holding it near CRs. Please update the README accordingly.

2021-08-05 23:11 UTC, apurwaj2 commented on examples/spark-3.1.1/apps/src/main/scala/com/hpe/examples/spark/sql/hive/SparkHiveExample.scala
> +  val warehouseLocation = "/opt/spark/work-dir/spark-warehouse"
Sure

2021-08-05 23:12 UTC, apurwaj2 commented on examples/spark-3.1.1/crs/hive/kv1.txt
> +238 val_238
That makes sense.

2021-08-16 15:10 UTC, AlexNavara approved these changes
lgtm

2021-08-17 16:51 UTC, merged