Add Spark Thrift Server V2.4.7 helm charts
HPEEzmeral/spark-on-k8s pull request #41
Opened 2021-08-14 02:46 UTC by akshayharyani

2021-08-16 18:27 UTC, AlexNavara requested changes

2021-08-16 18:27 UTC, AlexNavara commented on charts/spark-ts-2.4.7/spark-ts-chart/templates/serviceaccount.yaml
> +  name: {{ $componentName }}
Maybe we should put here "spark-ts-chart.serviceAccountName"?

2021-08-16 18:32 UTC, apurwaj2 commented
In the common.sh script of PKD, it expects POD_SERVICE_ACCOUNT ==  hpe-${POD_NAMESPACE}, to set ADMIN_SECRET to 'user' otherwise it is set to denied if a different service account. I don't know whether it affects thrift-server. It was an issue in case of hivemetastore and so I did not create a new service-account.  In case, you've already taken a look at this and you don't need to stick to using the hpe-${POD_NAMESPACE}, ignore the comment.

2021-08-16 19:03 UTC, akshayharyani commented on charts/spark-ts-2.4.7/spark-ts-chart/templates/serviceaccount.yaml
> +  name: {{ $componentName }}
I am copying  `spark-ts-chart.serviceAccountName` to a local variable called `componentName` and using it here and everywhere in this yaml. So the actual value will be same as of using `spark-ts-chart.serviceAccountName`

2021-08-16 20:27 UTC, AlexNavara commented on charts/spark-ts-2.4.7/spark-ts-chart/templates/serviceaccount.yaml
> +  name: {{ $componentName }}
Ok, thanks.

2021-08-16 20:27 UTC, AlexNavara approved these changes
lgtm

2021-08-16 21:12 UTC, apurwaj2 approved these changes
lgtm

2021-08-17 07:26 UTC, AlexNavara approved these changes

2021-08-17 17:11 UTC, merged