Adding Hivemetastore V2.4.7 helm chart
HPEEzmeral/spark-on-k8s pull request #42
Opened 2021-08-14 04:23 UTC by apurwaj2

Configuration for derby db.

2021-08-16 05:01 UTC, akshayharyani requested changes

2021-08-16 18:15 UTC, apurwaj2 commented on charts/metastore-2.4.7/hivemeta-chart/values.yaml
> +    - name: "CLUSTER_CREATE_TIME"
Done

2021-08-16 18:16 UTC, apurwaj2 commented on charts/metastore-2.4.7/hivemeta-chart/values.yaml
> +tenantNameSpace: sampletenant
Done.

2021-08-16 18:21 UTC, AlexNavara submitted a review, later dismissed
lgtm

2021-08-16 22:15 UTC, akshayharyani approved these changes
LGTM

2021-08-17 08:09 UTC, AlexNavara approved these changes

2021-08-17 16:50 UTC, merged