[WIP] EZSPA-300: Add support of S3 to spark-hs-3.1.1
HPEEzmeral/spark-on-k8s pull request #62
Opened 2021-09-27 14:51 UTC by avenherak

2021-09-29 06:07 UTC, akshayharyani requested changes

2021-09-29 06:07 UTC, akshayharyani commented on charts/spark-hs-3.1.1/spark-hs-chart/templates/deployment.yaml
> +          {{- else if .Values.s3.enableS3 }}
There is no content in this else if condition

2021-09-29 06:07 UTC, akshayharyani commented on charts/spark-hs-3.1.1/spark-hs-chart/values.yaml
> +#resources:
Resources were set by default in one of the previous commits. Why are we commenting them again?

2021-09-30 11:56 UTC, avenherak commented on charts/spark-hs-3.1.1/spark-hs-chart/templates/deployment.yaml
> +          {{- else if .Values.s3.enableS3 }}
simplified

2021-09-30 18:23 UTC, akshayharyani approved these changes

2021-10-01 06:27 UTC, merged